# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-15 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(max_length=128)),
                ('material_slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('special_considerations', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wasteprocessors.MaterialType')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofiles.Project')),
            ],
        ),
        migrations.CreateModel(
            name='WasteProcessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('business_hours', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=128)),
                ('will_pick_up', models.BooleanField(default=False)),
                ('will_purchase', models.BooleanField(default=False)),
                ('accepts_donations', models.BooleanField(default=False)),
                ('paid_service', models.BooleanField(default=False)),
                ('materials_accepted', models.ManyToManyField(related_name='material_types', to='wasteprocessors.MaterialType')),
            ],
        ),
        migrations.CreateModel(
            name='WasteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_type', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='wasteprocessor',
            name='waste_types_accepted',
            field=models.ManyToManyField(blank=True, related_name='waste_types', to='wasteprocessors.WasteType'),
        ),
        migrations.AddField(
            model_name='waste',
            name='waste_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wasteprocessors.WasteType'),
        ),
    ]
