# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-22 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasteprocessors', '0003_auto_20160422_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasteprocessor',
            name='address',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='wasteprocessor',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='wasteprocessor',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='wasteprocessor',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='wasteprocessor',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
