# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-22 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wasteprocessors', '0004_auto_20160422_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waste',
            name='material',
        ),
        migrations.AddField(
            model_name='waste',
            name='material_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wasteprocessors.MaterialType'),
        ),
    ]
