# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-10 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasteprocessors', '0005_auto_20160510_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasteprocessor',
            name='waste_types_accepted',
            field=models.ManyToManyField(blank=True, related_name='waste_types', to='wasteprocessors.WasteType'),
        ),
    ]
