# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-23 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasteprocessors', '0006_auto_20160423_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialtype',
            name='material_slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
