# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-10 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasteprocessors', '0006_auto_20160510_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasteprocessor',
            name='accepts_donations',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wasteprocessor',
            name='will_pick_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wasteprocessor',
            name='will_purchase',
            field=models.BooleanField(default=False),
        ),
    ]
